---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  namespace: drupal
spec:
  type: ClusterIP
  selector:
    app: drupal
  ports:
  - port: 8080
    targetPort: 80
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-external
  namespace: drupal
spec:
  type: LoadBalancer
  selector:
    app: drupal
  ports:
  - port: 80
    targetPort: 80
    name: http
